export const FETCH_POST_LIST = 'postList/FETCH_POST_LIST'
export const RESET_PAGE = 'postList/RESET_PAGE'
export const FETCH_MORE_POST_LIST = 'postList/FETCH_MORE_POST_LIST'
export const SET_SEARCH_KEYWORD = 'postList/SET_SEARCH_KEYWORD'
export const SET_SEARCH_TAGS = 'postList/SET_SEARCH_TAGS'
export const TOGGLE_SEARCH_TAG = 'postList/TOGGLE_SEARCH_TAG'
export const CLEAR_SEARCH = 'postList/CLEAR_SEARCH'
export const SET_SEARCH_PARAMS = 'postList/SET_SEARCH_PARAMS'
export const ADD_POST_LIST = 'postList/ADD_POST_LIST'
export const SET_ERROR = 'postList/SET_ERROR'

export const TOGGLE_SEARCH = 'ui/TOGGLE_SEARCH'
export const FLAG_SEARCH_ANIMATION_END = 'ui/FLAG_SEARCH_ANIMATION_END'
export const SET_TAGS = 'ui/SET_TAGS'
export const FETCH_TAGS = 'ui/FETCH_TAGS'

export const FETCH_NAV_LINKS = 'common/FETCH_NAV_LINKS'
export const SET_NAV_LINKS = 'common/SET_NAV_LINKS'
